import Head from "next/head";
import { withPageAuthRequired } from "@auth0/nextjs-auth0/client";

import Container from "../components/Container";

import styles from "../styles/home.module.css";

export default withPageAuthRequired(function Calendario() {
  return (
    <div className="">
      <Head>
        <title>Calendario</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <div className={styles.home}></div>
    </div>
  );
});
