import Head from "next/head";

import Navbar from "../components/Navbar";
import Container from "../components/Container";

import styles from "../styles/home.module.css";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Life Planner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <div className={styles.home}>
        <Navbar />
        {/*
        <div className={styles.main}>
          <Container type="large"></Container>
        </div>
  */}
      </div>
    </div>
  );
}
