import Head from "next/head";
import Link from "next/link";
import { useUser, withPageAuthRequired } from "@auth0/nextjs-auth0/client";

import axios from "axios";

import styles from "../styles/soprannome.module.css";
import { useState } from "react";

export default withPageAuthRequired(function Soprannome() {
  const [soprannome, setSoprannome] = useState("");

  const { user } = useUser();

  const updateUsername = () => {
    axios
      .put("/api/user", null, {
        params: {
          userId: user.sub,
          username: soprannome,
        },
      })
      .catch(function (error) {
        console.error(error);
      });
  };
  return (
    <div>
      <Head>
        <title>Soprannome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <div className={styles.container}>
        <div className={styles.title}>Inserisci un soprannome</div>
        <div className={styles.sub}>
          Il sopprannome verrà visualizzato al posto della propria email dagli
          altri utenti
        </div>
        <input
          className={styles.input}
          type="text"
          value={soprannome}
          onChange={(e) => {
            setSoprannome(e.target.value);
          }}
          placeholder="Inserisci soprannome"
        />
        <Link
          href="calendario"
          className={styles.continua}
          onClick={() => {
            updateUsername();
          }}
        >
          Continua
        </Link>
        <Link href="calendario" className={styles.salta}>
          Salta
        </Link>
      </div>
    </div>
  );
});
